name: reusable_build_tests_rust_pyo3

on:
  workflow_dispatch:
    inputs:
      py_interface_folder:
        description: "Location of the py interface folder"
        required: true
        type: string
      has_python_tests:
        description: "Is there a python_tests folder inside the python interface folder"
        required: false
        default: false
        type: boolean
      windows:
        description: "Run unittests on windows"
        required: false
        default: false
        type: boolean
      macos:
        description: "Run unittests on macOS"
        required: false
        default: true
        type: boolean
  workflow_call:
    inputs:
      py_interface_folder:
        description: "Location of the py interface folder"
        required: true
        type: string
      has_python_tests:
        description: "Is there a python_tests folder inside the python interface folder"
        required: false
        default: false
        type: boolean
      windows:
        description: "Run unittests on windows"
        required: false
        default: false
        type: boolean
      macos:
        description: "Run unittests on macOS"
        required: false
        default: true
        type: boolean

jobs:

  test_maturin_builds_linux:
    name: maturin_check_linux-${{ matrix.python.interpreter }}
    runs-on: "ubuntu-latest"
    strategy:
        python: [
            {py: '3.7', interpreter: "python3.7"},
            {py: '3.8', interpreter: "python3.8"},
            {py: '3.9', interpreter: "python3.9"},
            {py: '3.10', interpreter: "python3.10"},
            {py: '3.11', interpreter: "python3.11"},
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2.0.0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.py }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install maturin pytest numpy
          pip install ${{inputs.py_interface_folder}}
      - name: test
        run: |
          pytest ${{inputs.py_interface_folder}}/python_tests


  test_maturin_builds_windows:
    name: maturin_check_windows-${{ matrix.python.interpreter }}
    runs-on: "windows-latest"
    strategy:
        python: [
            {py: '3.7', interpreter: "python3.7"},
            {py: '3.8', interpreter: "python3.8"},
            {py: '3.9', interpreter: "python3.9"},
            {py: '3.10', interpreter: "python3.10"},
            {py: '3.11', interpreter: "python3.11"},
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2.0.0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.py }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install maturin pytest numpy
          pip install ${{inputs.py_interface_folder}}
      - name: test
        if: ${{inputs.has_python_tests}}
        run: |
          pytest ${{inputs.py_interface_folder}}/python_tests